# Generated by Django 3.0.6 on 2020-08-12 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Promo_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Desc', models.TextField(max_length=200)),
                ('Benefit', models.IntegerField(max_length=5)),
                ('Quantity', models.IntegerField(max_length=5)),
                ('Code', models.CharField(max_length=10, unique=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('End_date', models.DateTimeField()),
                ('Is_active', models.BooleanField(default=False)),
                ('Freq_of_use', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Promo_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('CR', 'RECRNTLY ADDED'), ('PE', 'Pending'), ('PR', 'Processing'), ('FL', 'Failed')], max_length=2)),
                ('payment_method', models.CharField(choices=[('CR', 'Credit Card'), ('CA', 'Cash'), ('EW', 'EWallet')], max_length=2)),
            ],
        ),
    ]
