# Generated by Django 3.0.6 on 2020-08-13 06:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promocode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo_code',
            old_name='Is_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='promo_code',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='client',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='promo_code',
            name='Benefit',
        ),
        migrations.RemoveField(
            model_name='promo_code',
            name='Code',
        ),
        migrations.RemoveField(
            model_name='promo_code',
            name='Desc',
        ),
        migrations.RemoveField(
            model_name='promo_code',
            name='End_date',
        ),
        migrations.RemoveField(
            model_name='promo_code',
            name='Freq_of_use',
        ),
        migrations.RemoveField(
            model_name='promo_code',
            name='Quantity',
        ),
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='promo_code',
            name='benefit',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)], verbose_name='Benefit in Cents'),
        ),
        migrations.AddField(
            model_name='promo_code',
            name='code',
            field=models.CharField(default='', max_length=5, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='promo_code',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='promo_code',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='promo_code',
            name='freq_of_use',
            field=models.PositiveIntegerField(default=1, verbose_name='No. of time used'),
        ),
        migrations.AddField(
            model_name='promo_code',
            name='quantity',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='promo_history',
            name='Promo_code_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='promocode.Promo_code'),
        ),
        migrations.AddField(
            model_name='promo_history',
            name='Transaction_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='promocode.Transactions'),
        ),
        migrations.AddField(
            model_name='promo_history',
            name='client_freq_use',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promo_history',
            name='client_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='promocode.Client'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='Amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(60)], verbose_name='Amount in Cents'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='Created_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transactions',
            name='Promo_code_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promocode.Promo_code'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='client_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='promocode.Client'),
        ),
        migrations.AlterField(
            model_name='promo_code',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promo_history',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
