# Generated by Django 3.0.6 on 2020-08-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0003_remove_promo_code_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo_code',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
